// Generated by rstantools.  Do not edit by hand.

/*
    TelemetrySpace is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TelemetrySpace is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with TelemetrySpace.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_COA_Tag_Integrated_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 60> locations_array__ =
  {" (found before start of program)",
  " (in 'COA_Tag_Integrated', line 31, column 2 to column 52)",
  " (in 'COA_Tag_Integrated', line 32, column 2 to column 25)",
  " (in 'COA_Tag_Integrated', line 35, column 2 to column 59)",
  " (in 'COA_Tag_Integrated', line 37, column 2 to column 59)",
  " (in 'COA_Tag_Integrated', line 65, column 3 to column 46)",
  " (in 'COA_Tag_Integrated', line 66, column 3 to column 43)",
  " (in 'COA_Tag_Integrated', line 42, column 2 to column 37)",
  " (in 'COA_Tag_Integrated', line 43, column 2 to column 26)",
  " (in 'COA_Tag_Integrated', line 47, column 11 to column 15)",
  " (in 'COA_Tag_Integrated', line 47, column 4 to column 59)",
  " (in 'COA_Tag_Integrated', line 50, column 6 to column 72)",
  " (in 'COA_Tag_Integrated', line 48, column 23 to line 51, column 5)",
  " (in 'COA_Tag_Integrated', line 48, column 4 to line 51, column 5)",
  " (in 'COA_Tag_Integrated', line 45, column 21 to line 52, column 3)",
  " (in 'COA_Tag_Integrated', line 45, column 2 to line 52, column 3)",
  " (in 'COA_Tag_Integrated', line 57, column 13 to column 17)",
  " (in 'COA_Tag_Integrated', line 57, column 6 to column 74)",
  " (in 'COA_Tag_Integrated', line 60, column 6 to column 72)",
  " (in 'COA_Tag_Integrated', line 55, column 23 to line 61, column 5)",
  " (in 'COA_Tag_Integrated', line 55, column 4 to line 61, column 5)",
  " (in 'COA_Tag_Integrated', line 54, column 20 to line 62, column 3)",
  " (in 'COA_Tag_Integrated', line 54, column 2 to line 62, column 3)",
  " (in 'COA_Tag_Integrated', line 3, column 2 to column 22)",
  " (in 'COA_Tag_Integrated', line 4, column 2 to column 22)",
  " (in 'COA_Tag_Integrated', line 5, column 2 to column 23)",
  " (in 'COA_Tag_Integrated', line 6, column 2 to column 23)",
  " (in 'COA_Tag_Integrated', line 8, column 2 to column 24)",
  " (in 'COA_Tag_Integrated', line 10, column 8 to column 12)",
  " (in 'COA_Tag_Integrated', line 10, column 14 to column 19)",
  " (in 'COA_Tag_Integrated', line 10, column 21 to column 25)",
  " (in 'COA_Tag_Integrated', line 10, column 2 to column 44)",
  " (in 'COA_Tag_Integrated', line 12, column 8 to column 13)",
  " (in 'COA_Tag_Integrated', line 12, column 15 to column 20)",
  " (in 'COA_Tag_Integrated', line 12, column 22 to column 26)",
  " (in 'COA_Tag_Integrated', line 12, column 2 to column 48)",
  " (in 'COA_Tag_Integrated', line 13, column 9 to column 13)",
  " (in 'COA_Tag_Integrated', line 13, column 2 to column 20)",
  " (in 'COA_Tag_Integrated', line 14, column 9 to column 13)",
  " (in 'COA_Tag_Integrated', line 14, column 2 to column 20)",
  " (in 'COA_Tag_Integrated', line 15, column 2 to column 17)",
  " (in 'COA_Tag_Integrated', line 16, column 2 to column 17)",
  " (in 'COA_Tag_Integrated', line 17, column 9 to column 14)",
  " (in 'COA_Tag_Integrated', line 17, column 2 to column 22)",
  " (in 'COA_Tag_Integrated', line 18, column 9 to column 14)",
  " (in 'COA_Tag_Integrated', line 18, column 2 to column 22)",
  " (in 'COA_Tag_Integrated', line 22, column 9 to column 14)",
  " (in 'COA_Tag_Integrated', line 22, column 16 to column 20)",
  " (in 'COA_Tag_Integrated', line 22, column 2 to column 26)",
  " (in 'COA_Tag_Integrated', line 24, column 4 to column 80)",
  " (in 'COA_Tag_Integrated', line 23, column 21 to line 25, column 3)",
  " (in 'COA_Tag_Integrated', line 23, column 2 to line 25, column 3)",
  " (in 'COA_Tag_Integrated', line 31, column 32 to column 37)",
  " (in 'COA_Tag_Integrated', line 31, column 39 to column 43)",
  " (in 'COA_Tag_Integrated', line 35, column 43 to column 47)",
  " (in 'COA_Tag_Integrated', line 35, column 49 to column 54)",
  " (in 'COA_Tag_Integrated', line 37, column 43 to column 47)",
  " (in 'COA_Tag_Integrated', line 37, column 49 to column 54)",
  " (in 'COA_Tag_Integrated', line 65, column 10 to column 15)",
  " (in 'COA_Tag_Integrated', line 65, column 17 to column 21)"};
#include <stan_meta_header.hpp>
class model_COA_Tag_Integrated final : public model_base_crtp<model_COA_Tag_Integrated> {
private:
  int nind;
  int nrec;
  int ntime;
  int ntest;
  int ntrans;
  std::vector<std::vector<std::vector<int>>> y;
  std::vector<std::vector<std::vector<int>>> test;
  Eigen::Matrix<double,-1,1> recX_data__;
  Eigen::Matrix<double,-1,1> recY_data__;
  Eigen::Matrix<double,-1,1> xlim_data__;
  Eigen::Matrix<double,-1,1> ylim_data__;
  Eigen::Matrix<double,-1,1> testX_data__;
  Eigen::Matrix<double,-1,1> testY_data__;
  Eigen::Matrix<double,-1,-1> td2_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> recX{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> recY{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> xlim{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> ylim{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> testX{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> testY{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> td2{nullptr, 0, 0};
public:
  ~model_COA_Tag_Integrated() {}
  model_COA_Tag_Integrated(stan::io::var_context& context__, unsigned int
                           random_seed__ = 0, std::ostream*
                           pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_COA_Tag_Integrated_namespace::model_COA_Tag_Integrated";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 23;
      context__.validate_dims("data initialization", "nind", "int",
        std::vector<size_t>{});
      nind = std::numeric_limits<int>::min();
      current_statement__ = 23;
      nind = context__.vals_i("nind")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "nind", nind, 0);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "nrec", "int",
        std::vector<size_t>{});
      nrec = std::numeric_limits<int>::min();
      current_statement__ = 24;
      nrec = context__.vals_i("nrec")[(1 - 1)];
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "nrec", nrec, 0);
      current_statement__ = 25;
      context__.validate_dims("data initialization", "ntime", "int",
        std::vector<size_t>{});
      ntime = std::numeric_limits<int>::min();
      current_statement__ = 25;
      ntime = context__.vals_i("ntime")[(1 - 1)];
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "ntime", ntime, 0);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "ntest", "int",
        std::vector<size_t>{});
      ntest = std::numeric_limits<int>::min();
      current_statement__ = 26;
      ntest = context__.vals_i("ntest")[(1 - 1)];
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "ntest", ntest, 0);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "ntrans", "int",
        std::vector<size_t>{});
      ntrans = std::numeric_limits<int>::min();
      current_statement__ = 27;
      ntrans = context__.vals_i("ntrans")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "ntrans", ntrans, 0);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("y", "nind", nind);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("y", "ntime", ntime);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("y", "nrec", nrec);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(nind),
          static_cast<size_t>(ntime), static_cast<size_t>(nrec)});
      y = std::vector<std::vector<std::vector<int>>>(nind,
            std::vector<std::vector<int>>(ntime,
              std::vector<int>(nrec, std::numeric_limits<int>::min())));
      {
        std::vector<int> y_flat__;
        current_statement__ = 31;
        y_flat__ = context__.vals_i("y");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
          current_statement__ = 31;
          for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
            current_statement__ = 31;
            for (int sym3__ = 1; sym3__ <= nind; ++sym3__) {
              current_statement__ = 31;
              stan::model::assign(y, y_flat__[(pos__ - 1)],
                "assigning variable y", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 31;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 31;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("test", "ntest", ntest);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("test", "ntime", ntime);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("test", "nrec", nrec);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "test", "int",
        std::vector<size_t>{static_cast<size_t>(ntest),
          static_cast<size_t>(ntime), static_cast<size_t>(nrec)});
      test = std::vector<std::vector<std::vector<int>>>(ntest,
               std::vector<std::vector<int>>(ntime,
                 std::vector<int>(nrec, std::numeric_limits<int>::min())));
      {
        std::vector<int> test_flat__;
        current_statement__ = 35;
        test_flat__ = context__.vals_i("test");
        current_statement__ = 35;
        pos__ = 1;
        current_statement__ = 35;
        for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
          current_statement__ = 35;
          for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
            current_statement__ = 35;
            for (int sym3__ = 1; sym3__ <= ntest; ++sym3__) {
              current_statement__ = 35;
              stan::model::assign(test, test_flat__[(pos__ - 1)],
                "assigning variable test", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 35;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "test", test, 0);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("recX", "nrec", nrec);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "recX", "double",
        std::vector<size_t>{static_cast<size_t>(nrec)});
      recX_data__ = Eigen::Matrix<double,-1,1>::Constant(nrec,
                      std::numeric_limits<double>::quiet_NaN());
      new (&recX) Eigen::Map<Eigen::Matrix<double,-1,1>>(recX_data__.data(),
        nrec);
      {
        std::vector<local_scalar_t__> recX_flat__;
        current_statement__ = 37;
        recX_flat__ = context__.vals_r("recX");
        current_statement__ = 37;
        pos__ = 1;
        current_statement__ = 37;
        for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
          current_statement__ = 37;
          stan::model::assign(recX, recX_flat__[(pos__ - 1)],
            "assigning variable recX", stan::model::index_uni(sym1__));
          current_statement__ = 37;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 38;
      stan::math::validate_non_negative_index("recY", "nrec", nrec);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "recY", "double",
        std::vector<size_t>{static_cast<size_t>(nrec)});
      recY_data__ = Eigen::Matrix<double,-1,1>::Constant(nrec,
                      std::numeric_limits<double>::quiet_NaN());
      new (&recY) Eigen::Map<Eigen::Matrix<double,-1,1>>(recY_data__.data(),
        nrec);
      {
        std::vector<local_scalar_t__> recY_flat__;
        current_statement__ = 39;
        recY_flat__ = context__.vals_r("recY");
        current_statement__ = 39;
        pos__ = 1;
        current_statement__ = 39;
        for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
          current_statement__ = 39;
          stan::model::assign(recY, recY_flat__[(pos__ - 1)],
            "assigning variable recY", stan::model::index_uni(sym1__));
          current_statement__ = 39;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 40;
      context__.validate_dims("data initialization", "xlim", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      xlim_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                      std::numeric_limits<double>::quiet_NaN());
      new (&xlim) Eigen::Map<Eigen::Matrix<double,-1,1>>(xlim_data__.data(),
        2);
      {
        std::vector<local_scalar_t__> xlim_flat__;
        current_statement__ = 40;
        xlim_flat__ = context__.vals_r("xlim");
        current_statement__ = 40;
        pos__ = 1;
        current_statement__ = 40;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 40;
          stan::model::assign(xlim, xlim_flat__[(pos__ - 1)],
            "assigning variable xlim", stan::model::index_uni(sym1__));
          current_statement__ = 40;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 41;
      context__.validate_dims("data initialization", "ylim", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      ylim_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                      std::numeric_limits<double>::quiet_NaN());
      new (&ylim) Eigen::Map<Eigen::Matrix<double,-1,1>>(ylim_data__.data(),
        2);
      {
        std::vector<local_scalar_t__> ylim_flat__;
        current_statement__ = 41;
        ylim_flat__ = context__.vals_r("ylim");
        current_statement__ = 41;
        pos__ = 1;
        current_statement__ = 41;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 41;
          stan::model::assign(ylim, ylim_flat__[(pos__ - 1)],
            "assigning variable ylim", stan::model::index_uni(sym1__));
          current_statement__ = 41;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 42;
      stan::math::validate_non_negative_index("testX", "ntest", ntest);
      current_statement__ = 43;
      context__.validate_dims("data initialization", "testX", "double",
        std::vector<size_t>{static_cast<size_t>(ntest)});
      testX_data__ = Eigen::Matrix<double,-1,1>::Constant(ntest,
                       std::numeric_limits<double>::quiet_NaN());
      new (&testX)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(testX_data__.data(), ntest);
      {
        std::vector<local_scalar_t__> testX_flat__;
        current_statement__ = 43;
        testX_flat__ = context__.vals_r("testX");
        current_statement__ = 43;
        pos__ = 1;
        current_statement__ = 43;
        for (int sym1__ = 1; sym1__ <= ntest; ++sym1__) {
          current_statement__ = 43;
          stan::model::assign(testX, testX_flat__[(pos__ - 1)],
            "assigning variable testX", stan::model::index_uni(sym1__));
          current_statement__ = 43;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 44;
      stan::math::validate_non_negative_index("testY", "ntest", ntest);
      current_statement__ = 45;
      context__.validate_dims("data initialization", "testY", "double",
        std::vector<size_t>{static_cast<size_t>(ntest)});
      testY_data__ = Eigen::Matrix<double,-1,1>::Constant(ntest,
                       std::numeric_limits<double>::quiet_NaN());
      new (&testY)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(testY_data__.data(), ntest);
      {
        std::vector<local_scalar_t__> testY_flat__;
        current_statement__ = 45;
        testY_flat__ = context__.vals_r("testY");
        current_statement__ = 45;
        pos__ = 1;
        current_statement__ = 45;
        for (int sym1__ = 1; sym1__ <= ntest; ++sym1__) {
          current_statement__ = 45;
          stan::model::assign(testY, testY_flat__[(pos__ - 1)],
            "assigning variable testY", stan::model::index_uni(sym1__));
          current_statement__ = 45;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 46;
      stan::math::validate_non_negative_index("td2", "ntest", ntest);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("td2", "nrec", nrec);
      current_statement__ = 48;
      td2_data__ = Eigen::Matrix<double,-1,-1>::Constant(ntest, nrec,
                     std::numeric_limits<double>::quiet_NaN());
      new (&td2) Eigen::Map<Eigen::Matrix<double,-1,-1>>(td2_data__.data(),
        ntest, nrec);
      current_statement__ = 51;
      for (int s = 1; s <= ntest; ++s) {
        current_statement__ = 49;
        stan::model::assign(td2,
          stan::math::to_row_vector(
            stan::math::add(
              stan::math::square(
                stan::math::subtract(recX,
                  stan::model::rvalue(testX, "testX",
                    stan::model::index_uni(s)))),
              stan::math::square(
                stan::math::subtract(recY,
                  stan::model::rvalue(testY, "testY",
                    stan::model::index_uni(s)))))), "assigning variable td2",
          stan::model::index_uni(s), stan::model::index_omni());
      }
      current_statement__ = 52;
      stan::math::validate_non_negative_index("alpha0", "ntime", ntime);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("alpha0", "nrec", nrec);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("sx", "nind", nind);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("sx", "ntime", ntime);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("sy", "nind", nind);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("sy", "ntime", ntime);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("p0", "ntime", ntime);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("p0", "nrec", nrec);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (ntime * nrec) + 1 + (nind * ntime) + (nind * ntime);
  }
  inline std::string model_name() const final {
    return "model_COA_Tag_Integrated";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_COA_Tag_Integrated_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,-1> alpha0 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(ntime, nrec,
          DUMMY_VAR__);
      current_statement__ = 1;
      alpha0 = in__.template read_constrain_lub<
                 Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(-5, 5,
                 lp__, ntime, nrec);
      local_scalar_t__ alpha1 = DUMMY_VAR__;
      current_statement__ = 2;
      alpha1 = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,-1> sx =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nind, ntime,
          DUMMY_VAR__);
      current_statement__ = 3;
      sx = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,-1>,
             jacobian__>(stan::model::rvalue(xlim, "xlim",
                           stan::model::index_uni(1)),
             stan::model::rvalue(xlim, "xlim", stan::model::index_uni(2)),
             lp__, nind, ntime);
      Eigen::Matrix<local_scalar_t__,-1,-1> sy =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nind, ntime,
          DUMMY_VAR__);
      current_statement__ = 4;
      sy = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,-1>,
             jacobian__>(stan::model::rvalue(ylim, "ylim",
                           stan::model::index_uni(1)),
             stan::model::rvalue(ylim, "ylim", stan::model::index_uni(2)),
             lp__, nind, ntime);
      {
        current_statement__ = 7;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(
                         stan::math::to_vector(alpha0), 0, 2.5));
        current_statement__ = 8;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(alpha1, 0, 2.5));
        current_statement__ = 15;
        for (int s = 1; s <= ntest; ++s) {
          current_statement__ = 9;
          stan::math::validate_non_negative_index("dist_decay", "nrec", nrec);
          Eigen::Matrix<local_scalar_t__,-1,1> dist_decay =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nrec, DUMMY_VAR__);
          current_statement__ = 10;
          stan::model::assign(dist_decay,
            stan::math::multiply(alpha1,
              stan::math::to_vector(
                stan::model::rvalue(td2, "td2", stan::model::index_uni(s),
                  stan::model::index_omni()))),
            "assigning variable dist_decay");
          current_statement__ = 13;
          for (int t = 1; t <= ntime; ++t) {
            current_statement__ = 11;
            lp_accum__.add(stan::math::binomial_logit_lpmf<propto__>(
                             stan::model::rvalue(test, "test",
                               stan::model::index_uni(s),
                               stan::model::index_uni(t)), ntrans,
                             stan::math::subtract(
                               stan::math::transpose(
                                 stan::math::row(alpha0, t)), dist_decay)));
          }
        }
        current_statement__ = 22;
        for (int i = 1; i <= nind; ++i) {
          current_statement__ = 20;
          for (int t = 1; t <= ntime; ++t) {
            current_statement__ = 16;
            stan::math::validate_non_negative_index("d2", "nrec", nrec);
            Eigen::Matrix<local_scalar_t__,-1,1> d2 =
              Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nrec,
                DUMMY_VAR__);
            current_statement__ = 17;
            stan::model::assign(d2,
              stan::math::add(
                stan::math::square(
                  stan::math::subtract(recX,
                    stan::model::rvalue(sx, "sx", stan::model::index_uni(i),
                      stan::model::index_uni(t)))),
                stan::math::square(
                  stan::math::subtract(recY,
                    stan::model::rvalue(sy, "sy", stan::model::index_uni(i),
                      stan::model::index_uni(t))))), "assigning variable d2");
            current_statement__ = 18;
            lp_accum__.add(stan::math::binomial_logit_lpmf<propto__>(
                             stan::model::rvalue(y, "y",
                               stan::model::index_uni(i),
                               stan::model::index_uni(t)), ntrans,
                             stan::math::subtract(
                               stan::math::transpose(
                                 stan::math::row(alpha0, t)),
                               stan::math::multiply(alpha1, d2))));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_COA_Tag_Integrated_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,-1> alpha0 =
        Eigen::Matrix<double,-1,-1>::Constant(ntime, nrec,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      alpha0 = in__.template read_constrain_lub<
                 Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(-5, 5,
                 lp__, ntime, nrec);
      double alpha1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      alpha1 = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,-1> sx =
        Eigen::Matrix<double,-1,-1>::Constant(nind, ntime,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      sx = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,-1>,
             jacobian__>(stan::model::rvalue(xlim, "xlim",
                           stan::model::index_uni(1)),
             stan::model::rvalue(xlim, "xlim", stan::model::index_uni(2)),
             lp__, nind, ntime);
      Eigen::Matrix<double,-1,-1> sy =
        Eigen::Matrix<double,-1,-1>::Constant(nind, ntime,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      sy = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,-1>,
             jacobian__>(stan::model::rvalue(ylim, "ylim",
                           stan::model::index_uni(1)),
             stan::model::rvalue(ylim, "ylim", stan::model::index_uni(2)),
             lp__, nind, ntime);
      out__.write(alpha0);
      out__.write(alpha1);
      out__.write(sx);
      out__.write(sy);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,-1> p0 =
        Eigen::Matrix<double,-1,-1>::Constant(ntime, nrec,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      stan::model::assign(p0, stan::math::inv_logit(alpha0),
        "assigning variable p0");
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      sigma = stan::math::sqrt((1.0 / (2.0 * alpha1)));
      out__.write(p0);
      out__.write(sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> alpha0 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(ntime, nrec,
          DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(alpha0,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(ntime, nrec),
        "assigning variable alpha0");
      out__.write_free_lub(-5, 5, alpha0);
      local_scalar_t__ alpha1 = DUMMY_VAR__;
      current_statement__ = 2;
      alpha1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha1);
      Eigen::Matrix<local_scalar_t__,-1,-1> sx =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nind, ntime,
          DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(sx,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(nind, ntime),
        "assigning variable sx");
      out__.write_free_lub(stan::model::rvalue(xlim, "xlim",
                             stan::model::index_uni(1)),
        stan::model::rvalue(xlim, "xlim", stan::model::index_uni(2)), sx);
      Eigen::Matrix<local_scalar_t__,-1,-1> sy =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nind, ntime,
          DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(sy,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(nind, ntime),
        "assigning variable sy");
      out__.write_free_lub(stan::model::rvalue(ylim, "ylim",
                             stan::model::index_uni(1)),
        stan::model::rvalue(ylim, "ylim", stan::model::index_uni(2)), sy);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha0", "double",
        std::vector<size_t>{static_cast<size_t>(ntime),
          static_cast<size_t>(nrec)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "alpha1", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "sx", "double",
        std::vector<size_t>{static_cast<size_t>(nind),
          static_cast<size_t>(ntime)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sy", "double",
        std::vector<size_t>{static_cast<size_t>(nind),
          static_cast<size_t>(ntime)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> alpha0 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(ntime, nrec,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> alpha0_flat__;
        current_statement__ = 1;
        alpha0_flat__ = context__.vals_r("alpha0");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(alpha0, alpha0_flat__[(pos__ - 1)],
              "assigning variable alpha0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lub(-5, 5, alpha0);
      local_scalar_t__ alpha1 = DUMMY_VAR__;
      current_statement__ = 2;
      alpha1 = context__.vals_r("alpha1")[(1 - 1)];
      out__.write_free_lb(0, alpha1);
      Eigen::Matrix<local_scalar_t__,-1,-1> sx =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nind, ntime,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sx_flat__;
        current_statement__ = 3;
        sx_flat__ = context__.vals_r("sx");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
            current_statement__ = 3;
            stan::model::assign(sx, sx_flat__[(pos__ - 1)],
              "assigning variable sx", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 3;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lub(stan::model::rvalue(xlim, "xlim",
                             stan::model::index_uni(1)),
        stan::model::rvalue(xlim, "xlim", stan::model::index_uni(2)), sx);
      Eigen::Matrix<local_scalar_t__,-1,-1> sy =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nind, ntime,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sy_flat__;
        current_statement__ = 4;
        sy_flat__ = context__.vals_r("sy");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
          current_statement__ = 4;
          for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
            current_statement__ = 4;
            stan::model::assign(sy, sy_flat__[(pos__ - 1)],
              "assigning variable sy", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 4;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lub(stan::model::rvalue(ylim, "ylim",
                             stan::model::index_uni(1)),
        stan::model::rvalue(ylim, "ylim", stan::model::index_uni(2)), sy);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha0", "alpha1", "sx", "sy"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"p0", "sigma"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    ntime),
                                                 static_cast<size_t>(nrec)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(nind),
                  static_cast<size_t>(ntime)},
                std::vector<size_t>{static_cast<size_t>(nind),
                  static_cast<size_t>(ntime)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(ntime),
               static_cast<size_t>(nrec)}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
        param_names__.emplace_back(std::string() + "alpha0" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "alpha1");
    for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
        param_names__.emplace_back(std::string() + "sx" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
        param_names__.emplace_back(std::string() + "sy" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
          param_names__.emplace_back(std::string() + "p0" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      param_names__.emplace_back(std::string() + "sigma");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
        param_names__.emplace_back(std::string() + "alpha0" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "alpha1");
    for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
        param_names__.emplace_back(std::string() + "sx" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
        param_names__.emplace_back(std::string() + "sy" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
          param_names__.emplace_back(std::string() + "p0" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      param_names__.emplace_back(std::string() + "sigma");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha0\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(ntime) + ",\"cols\":" + std::to_string(nrec) + "},\"block\":\"parameters\"},{\"name\":\"alpha1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sx\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nind) + ",\"cols\":" + std::to_string(ntime) + "},\"block\":\"parameters\"},{\"name\":\"sy\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nind) + ",\"cols\":" + std::to_string(ntime) + "},\"block\":\"parameters\"},{\"name\":\"p0\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(ntime) + ",\"cols\":" + std::to_string(nrec) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha0\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(ntime) + ",\"cols\":" + std::to_string(nrec) + "},\"block\":\"parameters\"},{\"name\":\"alpha1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sx\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nind) + ",\"cols\":" + std::to_string(ntime) + "},\"block\":\"parameters\"},{\"name\":\"sy\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nind) + ",\"cols\":" + std::to_string(ntime) + "},\"block\":\"parameters\"},{\"name\":\"p0\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(ntime) + ",\"cols\":" + std::to_string(nrec) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((ntime * nrec) + 1) + (nind * ntime)) +
      (nind * ntime));
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (((ntime *
      nrec) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((ntime * nrec) + 1) + (nind * ntime)) +
      (nind * ntime));
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (((ntime *
      nrec) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_COA_Tag_Integrated_namespace::model_COA_Tag_Integrated;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_COA_Tag_Integrated_namespace::profiles__;
}
#endif
#endif
